image: node:14.15.4
cache:
  paths:
    - node_modules/
deploy_stage:
  stage: deploy
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href http://productcatalog.surge.sh/
    - ./node_modules/.bin/surge -p dist/product-catalog-app/ --domain http://productcatalog.surge.sh/
